def get_affected_role(mutation_request):
    """
    Returns the role associated with the specific message we are requesting to mutate.

    Args:
        mutation_request (str): The type of mutation to apply.

    Returns:
        str: The role associated with the specific message we are requesting to mutate.
    """
    return "user" if mutation_request == "Topic dilution" else "tool"


def get_mutation_messages(mutation_request):
    """
    Returns the messages used to perform the mutation.

    Args:
        mutation_request (str): The type of mutation to apply.

    Returns:
        dict: The system message used to explain the the LLM's role.
        dict: The user message used to perform the mutation.
    """

    match mutation_request:
        case "Salience removal":
            # Salience removal involves deleting the passage whose tokens have the largest attribution with respect to the answer.
            # This means that we remove passages from the context that have the largest influence on the answer.

            return (
                {
                    "role": "system",
                    "content": (
                        "Your job is to identify and remove salient passages from tool results that help to inform the assistant response."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        "In our conversation, find the messages generated by tools that contain the results of tool calls.\n"
                        "For each one, identify the key points later used or paraphrased in the corresponding assistant response.\n"
                        "Then, remove only the most salient content from each tool content value - that is, the passage that most directly informs the assistant's reply.\n"
                        "When editing the objects, you must not remove any keys.\n"
                        "Return a dictionary that maps the tool content's referenceNumber as a string to the new edited object with that referenceNumber.\n"
                        "Return only the dictionary, with no extra commentary or explanation, on a single line without any indentation."
                    ),
                }
            )

        case "Claim-aligned deletion":
            # TODO
            pass

        case "Topic dilution":
            # Topic dilution involves injecting spelling errors, keyboard procimity errors, and visual similarity errors into the chat sample.
            # This is done to add noise to the prompt and the tool content.

            return (
                {
                    "role": "system",
                    "content": (
                        "Your job is to rewrite text with spelling errors, keyboard proximity errors, and visual similarity errors.\n"
                        "Keyboard proximity errors are errors that occur when a user accidentally types a key that is close to the intended key on the keyboard.\n"
                        "Visual similarity errors are errors that occur when a user types a character that looks similar to the intended character, such as '0' instead of 'O' or '1' instead of 'l'."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        "In our conversation, find the original user message. \n"
                        "Rewrite the user message to include realistic spelling mistakes, keyboard proximity errors, and visual similarity errors.\n"
                        "Return only the new user message, with no extra commentary or explanation."
                    ),
                }
            )

        case "Negated-evidence injection":
            # Negated-evidence injection involves injecting a passage that contradicts the answer.

            return (
                {
                    "role": "system",
                    "content": (
                        "Your job is to negate specified passages whilst maintaining correct grammar.\n"
                        "You must not modify any entity names, file names, references, or object keys."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        "In our conversation, find the messages generated by tools that contain the results of tool calls.\n" 
                        "For each one, identify the key points later used or paraphrased in the corresponding assistant response.\n" 
                        "Then, rewrite the tool content to negate these points using words such as 'not', such that they now contradict the general message of the assistant response.\n"
                        "Only negate general claims or facts (e.g., change 'X is true' to 'X is not true')\n"
                        "When editing the objects, you must not remove any keys.\n"
                        "You must not change the names of entities, files, or references.\n"
                        "Return a dictionary that maps the tool content's referenceNumber as a string to the new edited object with that referenceNumber.\n"  
                        "Return only the dictionary, with no extra commentary or explanation, on a single line without any indentation."
                    ),
                }
            )

        case "Date / number jitter":
            # Date / number jitter involves making date-swap and number-swap edits.

            return (
                {
                    "role": "system",
                    "content": (
                        "Your job is to introduce date and number jitter to given data.\n"
                        "This involves swapping out dates for different dates and numbers for different numbers.\n"
                        "When swapping out dates, ensure that the new dates are realistic and plausible, for example not swapping a data in the past for a data in the future."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        "In our conversation, find the messages generated by tools that contain the results of tool calls.\n"
                        "Then, rewrite the tool content to introduce date and number jitter by replacing dates with different dates and replacing numbers for different numbers. These numbers may include measurements, numerical labels, and section numbers.\n"
                        "You must not change anything that isn't a number or a date.\n"
                        "When editing the objects, you must not remove any keys.\n"
                        "Return a dictionary that maps the tool content's referenceNumber as a string to the new edited object with that referenceNumber.\n"
                        "Return only the dictionary, with no extra commentary or explanation, on a single line without any indentation."
                    ),
                }
            )

        case "Passage shuffle":
            # Passage shuffle randomises the passage order to test position bias.

            return (
                {
                    "role": "system",
                    "content": (
                        "Your job is to randomise and shuffle the order of passages in given data."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        "In our conversation, find the messages generated by tools that contain the results of tool calls.\n"
                        "Then, rewrite the tool content to randomise and shuffle the order of the passages.\n"
                        "When editing the objects, you must not remove any keys.\n"
                        "Return a dictionary that maps the tool content's referenceNumber as a string to the new edited object with that referenceNumber.\n"
                        "Return only the dictionary, with no extra commentary or explanation, on a single line without any indentation."
                    ),
                }
            )

        case "Entity swap":
            # Entity swapping involes replacing entities such as names, locations, dates, times, quantities with units, and organisations with a different entity of the same type, while keeping the context and meaning of the conversation intact.

            return (
                {
                    "role": "system",
                    "content": (
                        "Your job is to perform entity swapping on given data.\n"
                        "This involves replacing entities such as names, locations, dates, times, quantities with units, and organisations with a different entity of the same type.\n"
                        "These swaps must be consistent across different messages.\n"
                        "Entities must be swapped with other entities that have also been mentioned in the conversation."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        "In our conversation, find the messages generated by tools that contain the results of tool calls. \n"
                        "Also find the entities that are most relevant to the original user message, and the corresponding assistant response.\n"
                        "Then, rewrite the tool content of the messages found to swap entities with other entities of the same type that have also been mentioned in our conversation.\n"
                        "When editing the objects, you must not remove any keys.\n"
                        "Keep entity swaps consistent across different messages.\n"
                        "Return a dictionary that maps the tool content's referenceNumber as a string to the new edited object with that referenceNumber.\n"
                        "Return only the dictionary, with no extra commentary or explanation, on a single line without any indentation."
                    ),
                }
            )

        case "Document-snippet cut-off":
            # TODO
            pass

        case "Unit-conversion rewrite":
            # Unit-conversion rewrite involves rewriting the chat sample to change the units of measurement to a different unit that measures the same type of quantity, while keeping the numerical values unchanged.

            return (
                {
                    "role": "system",
                    "content": (
                        "Your job each unit to a different unit that measures the same type of quantity without changing the numerical value.\n"
                        "You do not perform mathematical conversions, you simply swap the unit for a different one in the same category.\n"
                        "Examples:\n"
                        "- Original: The distance is 5 kilometers.\n"
                        "- Modified: The distance is 5 miles.\n\n"
                        "- Original: The temperature is 20 degrees Celsius.\n"
                        "- Modified: The temperature is 20 degrees Fahrenheit.\n\n"
                        "- Original: She is 12 years old.\n"
                        "- Modified: She is 12 months old."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        "In our conversation, find the messages generated by tools that contain the results of tool calls.\n"
                        "Then, rewrite the tool content to change any unit mentioned to a different unit that measures the same type of quantity, leaving the numerical value unchanged.\n"
                        "When editing the objects, you must not remove any keys.\n"
                        "Return a dictionary that maps the tool content's referenceNumber as a string to the new edited object with that referenceNumber.\n"
                        "Return only the dictionary, with no extra commentary or explanation, on a single line without any indentation."
                    ),
                }
            )

        case "Ablate URL links":
            # Ablate URL links involves removing all URLs from the chat sample.
            # This means that the LLM does not have the the ability to access these information sources.

            return (
                {
                    "role": "system",
                    "content": (
                        "Your job is to remove all URLs from given data whilst maintaining correct grammar.\n"
                        "This might involve removing the surrounding phrase context, or replacing the URL with a placeholder."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        "In our conversation, find the messages generated by tools that contain the results of tool calls.\n"
                        "Then, rewrite the tool content to remove all URLs and their surrounding phrase context.\n"
                        "When editing the objects, you must not remove any keys.\n"
                        "Return a dictionary that maps the tool content's referenceNumber as a string to the new edited object with that referenceNumber.\n"
                        "Return only the dictionary, with no extra commentary or explanation, on a single line without any indentation."
                    ),
                }
            )

        case _:
            # Default case for free-form mutation requests

            return (
                {
                    "role": "system",
                    "content": (
                        "Your job is to perform a mutation request by modifying data from our conversation history."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        "In our conversation, find the messages generated by tools that contain the results of tool calls.\n"
                        f"Then, rewrite the tool content to do the following: {mutation_request}.\n"
                        "When editing the objects, you must not remove any keys.\n"
                        "Return a dictionary that maps the tool content's referenceNumber as a string to the new edited object with that referenceNumber.\n"
                        "Return only the dictionary, with no extra commentary or explanation, on a single line without any indentation.\n"
                    ),
                }
            )